#!/usr/bin/env python3
# Copyright (C) 2026 花吹雪又一年
#
# This file is part of Roco-Kingdom-Protocol-Parser (RKPP).
# Licensed under the GNU Affero General Public License v3.0 only (AGPL-3.0-only).
# You must retain the author attribution, this notice, the LICENSE file,
# and the NOTICE file in redistributions and derivative works.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the LICENSE
# file for more details.

"""Compatibility facade for protocol parsing helpers."""

from rkpp_proto_core import (
    buff_name,
    buffbase_name,
    collect_varints,
    dedupe_state_wrappers,
    extract_creature,
    extract_dynamic_skill_entries,
    extract_inner_message,
    extract_skills,
    extract_state_wrapper,
    extract_state_wrappers_from_record,
    extract_stats,
    field_groups,
    first_sub,
    first_text,
    maybe_signed64,
    maybe_utf8,
    normalize_c2s_opcode,
    normalize_skill_id,
    parse_inner1_detail,
    parse_inner200_detail,
    parse_inner390_detail,
    parse_inner51_detail,
    parse_proto_message,
    parse_record,
    parse_special_payload,
    parse_sstop_body,
    parse_tgcp_control_packet,
    pet_name,
    pick_first,
    read_varint,
    side_name,
    skill_meta,
    skill_name,
    sstop_code_name,
    strip_tsf4g_padding,
    summarize_types,
    tgcp_command_name,
    tsf4g_trailer_len,
    type_name,
    walk_messages,
)
from rkpp_proto_battle import (
    _extract_perform_cmd,
    extract_0102_creatures,
    extract_0102_metadata,
    extract_01a9_action,
    extract_0220_handle,
    extract_130b_skill_select,
    extract_130c_result,
    extract_1312_round_flow,
    extract_1316_enter,
    extract_131a_round_start,
    extract_1322_skill_declare,
    extract_1324_action,
    extract_132c_finish,
    extract_13f3_preplay,
    extract_13f4_refresh,
    extract_13fc_pvp_perform,
)

__all__ = [
    "_extract_perform_cmd",
    "buff_name",
    "buffbase_name",
    "collect_varints",
    "dedupe_state_wrappers",
    "extract_0102_creatures",
    "extract_0102_metadata",
    "extract_01a9_action",
    "extract_0220_handle",
    "extract_130b_skill_select",
    "extract_130c_result",
    "extract_1312_round_flow",
    "extract_1316_enter",
    "extract_131a_round_start",
    "extract_1322_skill_declare",
    "extract_1324_action",
    "extract_132c_finish",
    "extract_13f3_preplay",
    "extract_13f4_refresh",
    "extract_13fc_pvp_perform",
    "extract_creature",
    "extract_dynamic_skill_entries",
    "extract_inner_message",
    "extract_skills",
    "extract_state_wrapper",
    "extract_state_wrappers_from_record",
    "extract_stats",
    "field_groups",
    "first_sub",
    "first_text",
    "maybe_signed64",
    "maybe_utf8",
    "normalize_c2s_opcode",
    "normalize_skill_id",
    "parse_inner1_detail",
    "parse_inner200_detail",
    "parse_inner390_detail",
    "parse_inner51_detail",
    "parse_proto_message",
    "parse_record",
    "parse_special_payload",
    "parse_sstop_body",
    "parse_tgcp_control_packet",
    "pet_name",
    "pick_first",
    "read_varint",
    "side_name",
    "skill_meta",
    "skill_name",
    "sstop_code_name",
    "strip_tsf4g_padding",
    "summarize_types",
    "tgcp_command_name",
    "tsf4g_trailer_len",
    "type_name",
    "walk_messages",
]
